### ISSUE TITLE
Get rid of perl dependency

### ISSUE THREAD

**Issue by baracoder** [jf647/btrfs-snap#14]
I would like to use btrfs-snap on a system where there is no perl installed (CoreOS)

Is it be possible to get rid of perl in this line? https://github.com/jf647/btrfs-snap/blob/master/btrfs-snap#L179

**Comment by serpedon** [comment]
Since this line #179 only line perl is used, I think the regex can be
replaced by a bash-only line. Feel free to create a pull request. I am
happy to review the changes.

Best,
Michael

**Comment by baracoder** [comment]
Created a pull request
