### ISSUE TITLE
No go with VFS

### ISSUE THREAD

**Issue by clawes** [jf647/btrfs-snap#9]
Just downloaded your script to help me automate btrfs snapshot.  Unfortunately, it doesn't work when the VFS option is used:

# ./btrfs_snap -r  -c -d .snapshots  -t 300 /btrfs/backup/nearline VFS 4
Create a readonly snapshot of '/btrfs/backup/nearline' in '/btrfs/backup/nearline/.snapshots/@GMT-2016.02.19-19.01.35'
ls: cannot access /btrfs/backup/nearline/.snapshots//btrfs/backup/nearline: No such file or directory
ls: cannot access VFS: No such file or directory
ls: cannot access 4GMT-????.??.??-??.??.??: No such file or directory

However this works:

 ./btrfs_snap -r  -c -d .snapshots  -t 300 /btrfs/backup/nearline hourly 4
Create a readonly snapshot of '/btrfs/backup/nearline' in '/btrfs/backup/nearline/.snapshots/hourly_2016-02-19_14-06-15'

Note, the  error only occurs when the VFS prefix is used.
----
What am I doing wrong?
OS:  CentOS 7 64-bit

**Comment by serpedon** [comment]
Thank you for reporting the problem.

You are completely right. The script is broken when the VFS option is
used. (Your specified command line was correct and SHOULD have worked.)

I believe that I fixed the bug by removing a $-sign which I 	incorrectly
put in myself. (See new version in the master branch.)

Could you please check if the script is now working for you? (On my
machine it now works.)

Best
Michael

PS: Please let me know if there are still any problems but be warned
that I'll be away for about the next two weeks.

**Comment by clawes** [comment]
Thanks for the quick response. I will try the new code later this evening and let you know the result. Cheers                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Michael WalzSent: Friday, February 19, 2016 3:04 PMTo: jf647/btrfs-snapReply To: jf647/btrfs-snapCc: clawesSubject: Re: [btrfs-snap] No go with VFS (#9)Thank you for reporting the problem.

You are completely right. The script is broken when the VFS option is
used. (Your specified command line was correct and SHOULD have worked.)

I believe that I fixed the bug by removing a $-sign which I 	incorrectly
put in myself. (See new version in the master branch.)

Could you please check if the script is now working for you? (On my
machine it now works.)

Best
Michael

PS: Please let me know if there are still any problems but be warned
that I'll be away for about the next two weeks.


—Reply to this email directly or view it on GitHub.

**Comment by clawes** [comment]
Michael,

I just tested the your updated script and the VFS prefix now works as expected.
Thanks!
